title: TechExeter Conference 2022
description: > # this means to ignore newlines until "baseurl:"
  Thursday 15th September 2022 at the University of Exeter
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://conference.techexeter.uk" # the base hostname & protocol for your site, e.g. http://example.com


# author:
#   name: 'Viktoriya Kapitonenko'
#   last_name: 'Kapitonenko'
#   cv: '//kaptn.ru'
#   avatar: '/images/avatar.jpeg'
#   github_username:  kaptn3  
#   email: vika@kaptn.ru
#   vk_id: id201664979
#   telegram_name: vikapitoshka 
#   logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html

include:
  - _pages
  
future: true

collections:
  speakers:
    output: true
    permalink: /:collection/:name.html
    sort_by: timeslot
  sponsors:
    output: false

# Defaults
defaults:
  # _speakers
  - scope:
      path: ""
      type: speakers
    values:
      layout: speakers
      schedule-ignore: false